[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "16"

[context.production.environment]
  FIREBASE_API_KEY = "${FIREBASE_API_KEY}"
  FIREBASE_AUTH_DOMAIN = "${FIREBASE_AUTH_DOMAIN}"
  FIREBASE_PROJECT_ID = "${FIREBASE_PROJECT_ID}"
  FIREBASE_STORAGE_BUCKET = "${FIREBASE_STORAGE_BUCKET}"
  FIREBASE_MESSAGING_SENDER_ID = "${FIREBASE_MESSAGING_SENDER_ID}"
  FIREBASE_APP_ID = "${FIREBASE_APP_ID}"

# Block access to sensitive files
[[redirects]]
  from = "/.env*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/admin/firebase-config.js"
  to = "/404.html"
  status = 404

# Security headers for admin
[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Security-Policy = "default-src 'self' https://www.gstatic.com https://fonts.googleapis.com https://fonts.gstatic.com https://*.firebaseapp.com https://*.googleapis.com https://securetoken.googleapis.com https://identitytoolkit.googleapis.com https://apis.google.com; script-src 'self' 'unsafe-inline' https://www.gstatic.com https://apis.google.com https://*.firebaseapp.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; connect-src 'self' https://*.firebaseapp.com https://*.googleapis.com https://securetoken.googleapis.com https://identitytoolkit.googleapis.com;"
    Expires = "0"
    Pragma = "no-cache"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Security headers for login
[[headers]]
  for = "/login.html"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://www.gstatic.com https://fonts.googleapis.com https://fonts.gstatic.com https://*.firebaseapp.com https://*.googleapis.com https://securetoken.googleapis.com https://identitytoolkit.googleapis.com https://apis.google.com; script-src 'self' 'unsafe-inline' https://www.gstatic.com https://apis.google.com https://*.firebaseapp.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; connect-src 'self' https://*.firebaseapp.com https://*.googleapis.com https://securetoken.googleapis.com https://identitytoolkit.googleapis.com;"
    X-Frame-Options = "DENY"
    Cache-Control = "no-cache, no-store, must-revalidate"
    X-Content-Type-Options = "nosniff"

[functions]
  node_bundler = "esbuild"