[build]
  publish = "."                    # or your actual public folder, e.g., "dist"
  functions = "netlify/functions"  # serverless functions folder

# Block access to sensitive files
[[redirects]]
  from = "/.env*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/admin/firebase-config.js"
  to = "/404.html"
  status = 404

# Security headers for admin
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-cache, no-store, must-revalidate"
