name: Update Gallery

on:
  push:
    paths:
      - "uploads/gallery/*.jpg"
      - "uploads/gallery/*.png"
      - "uploads/gallery/*.webp"

jobs:
  update-gallery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        working-directory: uploads/gallery

      - name: Run gallery generator
        run: node generate-gallery.js
        working-directory: uploads/gallery

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add uploads/gallery/gallery.json
          git commit -m "Auto update gallery.json"
          git push
